import type {
  BudgetItem,
  Contract,
  Product,
  ProductModule,
  Reseller,
  Vendor,
} from "@/types/portfolio";

export const portfolioVendors: Vendor[] = [
  { id: "rapid7", name: "Rapid7", type: "Vendor" },
  { id: "sentinelone", name: "SentinelOne", type: "Vendor" },
  { id: "okta", name: "Okta", type: "Vendor" },
  { id: "mimecast", name: "Mimecast", type: "Vendor" },
  { id: "knowbe4", name: "KnowBe4", type: "Vendor" },
  { id: "onetrust", name: "OneTrust", type: "Vendor" },
  { id: "wiz", name: "Wiz", type: "Vendor" },
  { id: "palo-alto", name: "Palo Alto Networks", type: "Vendor" },
  { id: "microsoft", name: "Microsoft Purview", type: "Vendor" },
  { id: "cisco", name: "Cisco Umbrella", type: "Vendor" },
  { id: "sans", name: "SANS Institute", type: "Vendor" },
];

export const portfolioResellers: Reseller[] = [
  { id: "direct", name: "Direct" },
  { id: "shi", name: "SHI Government Solutions" },
  { id: "cdwg", name: "CDW-G" },
  { id: "guidepoint", name: "GuidePoint Security" },
];

export const budgetItems: BudgetItem[] = [
  {
    id: "budget-rapid7",
    budgetYear: "FY2027",
    budgetCategory: "Vulnerability & Exposure Management",
    expenseType: "Software / SaaS",
    vendorId: "rapid7",
    productOrServiceName: "InsightVM renewal",
    description: "Exposure management platform renewal and remediation module.",
    budgetedAmount: 295000,
    forecastedAmount: 315000,
    actualAmount: 0,
    fundingStatus: "Requested",
    owner: "Jordan Rivera",
    businessJustification:
      "Maintains enterprise vulnerability prioritization and remediation reporting.",
    riskIfNotFunded:
      "Loss of exposure visibility would slow remediation governance and executive risk reporting.",
    notes: "Confirm remediation project seat count before final approval.",
    contractId: "contract-rapid7",
    productId: "product-rapid7",
  },
  {
    id: "budget-s1",
    budgetYear: "FY2027",
    budgetCategory: "Endpoint Security",
    expenseType: "Subscription",
    vendorId: "sentinelone",
    resellerId: "cdwg",
    productOrServiceName: "Singularity Complete",
    description: "Endpoint protection and response coverage.",
    budgetedAmount: 420000,
    forecastedAmount: 430000,
    actualAmount: 105000,
    fundingStatus: "Approved",
    owner: "Maya Chen",
    businessJustification:
      "Baseline EDR coverage for corporate and privileged workstations.",
    riskIfNotFunded:
      "Endpoint detection coverage would fall below response plan assumptions.",
    notes: "Purchased through CDW-G reseller vehicle.",
    contractId: "contract-s1",
    productId: "product-s1",
  },
  {
    id: "budget-okta",
    budgetYear: "FY2027",
    budgetCategory: "Identity & Access Management",
    expenseType: "Software / SaaS",
    vendorId: "okta",
    resellerId: "shi",
    productOrServiceName: "Okta Identity Cloud",
    description: "SSO, MFA, and lifecycle management renewal.",
    budgetedAmount: 510000,
    forecastedAmount: 500000,
    actualAmount: 250000,
    fundingStatus: "Approved",
    owner: "Priya Shah",
    businessJustification:
      "Preserves enterprise access controls and identity governance integration.",
    riskIfNotFunded:
      "Manual access processes and weaker MFA enforcement would increase identity risk.",
    notes: "Forecast assumes no new workforce expansion.",
    contractId: "contract-okta",
    productId: "product-okta",
  },
  {
    id: "budget-knowbe4",
    budgetYear: "FY2027",
    budgetCategory: "Workforce Security Awareness",
    expenseType: "Training",
    vendorId: "knowbe4",
    productOrServiceName: "Security Awareness Training",
    description: "Workforce security awareness and phishing simulation.",
    budgetedAmount: 85000,
    forecastedAmount: 85000,
    actualAmount: 85000,
    fundingStatus: "Approved",
    owner: "Alex Morgan",
    businessJustification:
      "Supports enterprise-wide behavior change and recurring phishing simulations.",
    riskIfNotFunded:
      "Reduced awareness cadence would weaken employee reporting and preparedness.",
    notes: "Direct vendor spend; separate from professional staff training.",
    productId: "product-knowbe4",
  },
  {
    id: "budget-sans",
    budgetYear: "FY2027",
    budgetCategory: "Cybersecurity Staff Training & Development",
    expenseType: "Certification",
    vendorId: "sans",
    resellerId: "guidepoint",
    productOrServiceName: "SANS technical training vouchers",
    description:
      "Role-based security engineering and incident response training.",
    budgetedAmount: 140000,
    forecastedAmount: 165000,
    actualAmount: 42000,
    fundingStatus: "Partially Approved",
    owner: "Nolan Brooks",
    businessJustification:
      "Maintains analyst and engineer depth for incident response and cloud security work.",
    riskIfNotFunded:
      "Critical staff certifications and advanced response skills would lag the threat profile.",
    notes: "Shows staff development separately from workforce awareness.",
    productId: "product-sans",
  },
  {
    id: "budget-wiz",
    budgetYear: "FY2027",
    budgetCategory: "Cloud Security",
    expenseType: "Cloud / Infrastructure",
    vendorId: "wiz",
    resellerId: "shi",
    productOrServiceName: "Wiz CNAPP expansion",
    description: "Cloud security posture and workload protection expansion.",
    budgetedAmount: 360000,
    forecastedAmount: 390000,
    actualAmount: 0,
    fundingStatus: "Deferred",
    owner: "Taylor Reed",
    businessJustification:
      "Expands multi-cloud posture visibility for cloud engineering teams.",
    riskIfNotFunded:
      "Cloud exposure review remains fragmented across environments.",
    notes: "Deferred pending cloud platform roadmap decision.",
    productId: "product-wiz",
  },
  {
    id: "budget-cisco",
    budgetYear: "FY2027",
    budgetCategory: "Network Security",
    expenseType: "Subscription",
    vendorId: "cisco",
    resellerId: "cdwg",
    productOrServiceName: "Cisco Umbrella DNS Security",
    description: "DNS-layer protection renewal.",
    budgetedAmount: 180000,
    forecastedAmount: 170000,
    actualAmount: 188000,
    fundingStatus: "Approved",
    owner: "Sam Patel",
    businessJustification:
      "Maintains DNS security controls for users and branch locations.",
    riskIfNotFunded:
      "Loss of DNS-layer protection would increase commodity malware exposure.",
    notes: "Actual came in above budget after seat true-up.",
    contractId: "contract-cisco",
    productId: "product-cisco",
  },
  {
    id: "budget-onetrust",
    budgetYear: "FY2027",
    budgetCategory: "Governance, Risk & Compliance",
    expenseType: "Professional Service",
    vendorId: "onetrust",
    productOrServiceName: "Third-party risk module expansion",
    description: "GRC expansion for vendor risk intake.",
    budgetedAmount: 210000,
    forecastedAmount: 210000,
    actualAmount: 0,
    fundingStatus: "Unfunded",
    owner: "Jordan Rivera",
    businessJustification:
      "Would consolidate supplier security questionnaires and executive reporting.",
    riskIfNotFunded:
      "Vendor risk intake remains manual and difficult to report.",
    notes: "Candidate for next planning cycle.",
    productId: "product-onetrust",
  },
];

export const contracts: Contract[] = [
  {
    id: "contract-rapid7",
    vendorId: "rapid7",
    contractName: "Rapid7 Insight Platform Renewal",
    contractType: "SaaS",
    associatedProductOrService: "InsightVM",
    startDate: "2026-04-01",
    endDate: "2027-03-31",
    renewalDate: "2026-08-05",
    autoRenewal: false,
    noticePeriodDays: 60,
    annualContractValue: 295000,
    totalContractValue: 295000,
    paymentFrequency: "Annual",
    contractOwner: "Jordan Rivera",
    businessOwner: "Security Operations",
    securityOwner: "Exposure Management",
    procurementContact: "Casey Nguyen",
    vendorAccountManager: "Dana Burke",
    contractStatus: "Renewing",
    renewalRiskLevel: "High",
    renewalStrategy: "Renew after module rationalization and seat review.",
    notes: "Notice deadline is the controlling urgency date.",
    productIds: ["product-rapid7"],
  },
  {
    id: "contract-s1",
    vendorId: "sentinelone",
    resellerId: "cdwg",
    contractName: "SentinelOne Endpoint Protection",
    contractType: "SaaS",
    associatedProductOrService: "Singularity Complete",
    startDate: "2026-09-01",
    endDate: "2027-08-31",
    renewalDate: "2027-07-01",
    autoRenewal: false,
    noticePeriodDays: 90,
    annualContractValue: 420000,
    totalContractValue: 420000,
    paymentFrequency: "Annual",
    contractOwner: "Maya Chen",
    businessOwner: "Infrastructure",
    securityOwner: "Endpoint Security",
    procurementContact: "Casey Nguyen",
    vendorAccountManager: "Riley Ortiz",
    resellerAccountManager: "Chris Harper",
    contractStatus: "Active",
    renewalRiskLevel: "Medium",
    renewalStrategy: "Benchmark MDR bundle before renewal.",
    notes: "Reseller-supported contract through CDW-G.",
    productIds: ["product-s1"],
  },
  {
    id: "contract-okta",
    vendorId: "okta",
    resellerId: "shi",
    contractName: "Okta Identity Cloud Renewal",
    contractType: "SaaS",
    associatedProductOrService: "SSO, MFA, Lifecycle",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    renewalDate: "2026-07-25",
    autoRenewal: true,
    noticePeriodDays: 75,
    annualContractValue: 500000,
    totalContractValue: 1000000,
    paymentFrequency: "Annual",
    contractOwner: "Priya Shah",
    businessOwner: "Digital Workplace",
    securityOwner: "Identity Security",
    procurementContact: "Morgan Lee",
    vendorAccountManager: "Samir Awan",
    resellerAccountManager: "Leslie Kim",
    contractStatus: "Expiring Soon",
    renewalRiskLevel: "Critical",
    renewalStrategy:
      "Negotiate expansion guardrails before auto-renewal notice.",
    notes: "Auto-renewal requires executive decision before notice date.",
    productIds: ["product-okta"],
  },
  {
    id: "contract-cisco",
    vendorId: "cisco",
    resellerId: "cdwg",
    contractName: "Cisco Umbrella DNS Security",
    contractType: "Software",
    associatedProductOrService: "Umbrella DNS Security",
    startDate: "2026-06-01",
    endDate: "2027-05-31",
    renewalDate: "2026-10-15",
    autoRenewal: false,
    noticePeriodDays: 45,
    annualContractValue: 180000,
    totalContractValue: 180000,
    paymentFrequency: "Annual",
    contractOwner: "Sam Patel",
    businessOwner: "Network Engineering",
    securityOwner: "Network Security",
    procurementContact: "Morgan Lee",
    vendorAccountManager: "Terry Grant",
    resellerAccountManager: "Chris Harper",
    contractStatus: "Active",
    renewalRiskLevel: "Low",
    renewalStrategy: "Renew unless SASE consolidation changes scope.",
    notes: "Reseller-tied spend used for reseller reporting.",
    productIds: ["product-cisco"],
  },
];

export const products: Product[] = [
  {
    id: "product-rapid7",
    vendorId: "rapid7",
    productName: "InsightVM",
    productCategory: "Vulnerability & Exposure Management",
    capabilityCategory: "Vulnerability Management",
    description: "Vulnerability and exposure management platform.",
    deploymentStatus: "Active",
    businessOwner: "Security Operations",
    technicalOwner: "Exposure Engineering",
    securityOwner: "Jordan Rivera",
    primaryUseCase: "Prioritize vulnerabilities and exposure remediation.",
    strategicValue: "High",
    criticality: "High",
    annualCost: 295000,
    contractId: "contract-rapid7",
    budgetItemId: "budget-rapid7",
    notes: "Renewal under review for module utilization.",
  },
  {
    id: "product-s1",
    vendorId: "sentinelone",
    resellerId: "cdwg",
    productName: "Singularity Complete",
    productCategory: "Endpoint Security",
    capabilityCategory: "EDR",
    description: "Endpoint detection, response, and protection.",
    deploymentStatus: "Active",
    businessOwner: "Infrastructure",
    technicalOwner: "Endpoint Engineering",
    securityOwner: "Maya Chen",
    primaryUseCase: "Endpoint threat detection and automated response.",
    strategicValue: "Critical",
    criticality: "Critical",
    annualCost: 420000,
    contractId: "contract-s1",
    budgetItemId: "budget-s1",
    notes: "Primary endpoint security platform.",
  },
  {
    id: "product-okta",
    vendorId: "okta",
    resellerId: "shi",
    productName: "Okta Identity Cloud",
    productCategory: "Identity & Access",
    capabilityCategory: "SSO",
    description: "Enterprise identity, SSO, MFA, and lifecycle platform.",
    deploymentStatus: "Active",
    businessOwner: "Digital Workplace",
    technicalOwner: "Identity Platform",
    securityOwner: "Priya Shah",
    primaryUseCase: "SSO and adaptive MFA for workforce access.",
    strategicValue: "Critical",
    criticality: "Critical",
    annualCost: 500000,
    contractId: "contract-okta",
    budgetItemId: "budget-okta",
    notes: "Auto-renewal risk requires active management.",
  },
  {
    id: "product-knowbe4",
    vendorId: "knowbe4",
    productName: "Security Awareness Training",
    productCategory: "Workforce Security Awareness",
    capabilityCategory: "Security Awareness",
    description: "Workforce awareness training and phishing simulations.",
    deploymentStatus: "Active",
    businessOwner: "People Operations",
    technicalOwner: "Security Awareness",
    securityOwner: "Alex Morgan",
    primaryUseCase:
      "Enterprise-wide security awareness and phishing readiness.",
    strategicValue: "High",
    criticality: "Medium",
    annualCost: 85000,
    budgetItemId: "budget-knowbe4",
    notes: "Awareness category is distinct from staff development.",
  },
  {
    id: "product-sans",
    vendorId: "sans",
    resellerId: "guidepoint",
    productName: "SANS Training Vouchers",
    productCategory: "Cybersecurity Staff Training & Development",
    capabilityCategory: "Certification Training",
    description:
      "Technical training and certification vouchers for security staff.",
    deploymentStatus: "Active",
    businessOwner: "Cybersecurity Leadership",
    technicalOwner: "Security Enablement",
    securityOwner: "Nolan Brooks",
    primaryUseCase:
      "Staff upskilling for cloud security and incident response.",
    strategicValue: "High",
    criticality: "Medium",
    annualCost: 140000,
    budgetItemId: "budget-sans",
    notes: "Shows staff development separately from workforce awareness.",
  },
  {
    id: "product-wiz",
    vendorId: "wiz",
    resellerId: "shi",
    productName: "Wiz CNAPP",
    productCategory: "Cloud Security",
    capabilityCategory: "CNAPP",
    description: "Cloud-native application protection and posture management.",
    deploymentStatus: "Under Review",
    businessOwner: "Cloud Platform",
    technicalOwner: "Cloud Security Engineering",
    securityOwner: "Taylor Reed",
    primaryUseCase:
      "Cloud posture, workload exposure, and risk prioritization.",
    strategicValue: "High",
    criticality: "High",
    annualCost: 360000,
    budgetItemId: "budget-wiz",
    notes: "Expansion deferred pending platform roadmap.",
  },
  {
    id: "product-cisco",
    vendorId: "cisco",
    resellerId: "cdwg",
    productName: "Umbrella DNS Security",
    productCategory: "Network Security",
    capabilityCategory: "DNS Security",
    description: "DNS-layer security and threat blocking.",
    deploymentStatus: "Active",
    businessOwner: "Network Engineering",
    technicalOwner: "Network Security Engineering",
    securityOwner: "Sam Patel",
    primaryUseCase:
      "Secure web gateway and DNS security for users and branch networks.",
    strategicValue: "Medium",
    criticality: "High",
    annualCost: 180000,
    contractId: "contract-cisco",
    budgetItemId: "budget-cisco",
    notes: "Potential overlap with SASE roadmap.",
  },
  {
    id: "product-palo-alto",
    vendorId: "palo-alto",
    productName: "Prisma Access",
    productCategory: "Network Security",
    capabilityCategory: "Secure Web Gateway",
    description: "SASE and secure web gateway platform under evaluation.",
    deploymentStatus: "Planned",
    businessOwner: "Network Engineering",
    technicalOwner: "Network Architecture",
    securityOwner: "Sam Patel",
    primaryUseCase: "Secure web gateway and remote access modernization.",
    strategicValue: "High",
    criticality: "Medium",
    annualCost: 0,
    notes:
      "Potential redundancy indicator with Umbrella until architecture decision.",
  },
];

export const productModules: ProductModule[] = [
  {
    id: "module-rapid7-remediation",
    productId: "product-rapid7",
    moduleName: "Remediation Projects",
    description: "Workflow support for remediation owners.",
    capabilityModuleCategory: "Exposure Management",
    enabled: true,
    adoptionLevel: "Low",
    licenseCount: 1500,
    usedCount: 420,
    moduleCost: 45000,
    owner: "Exposure Engineering",
    notes: "Low adoption makes this a renewal review point.",
  },
  {
    id: "module-s1-cloud",
    productId: "product-s1",
    moduleName: "Cloud Workload Security",
    description: "Runtime workload protection add-on.",
    capabilityModuleCategory: "CWPP",
    enabled: true,
    adoptionLevel: "Medium",
    licenseCount: 700,
    usedCount: 390,
    moduleCost: 85000,
    owner: "Cloud Security Engineering",
    notes: "Adoption improving after Linux rollout.",
  },
  {
    id: "module-okta-mfa",
    productId: "product-okta",
    moduleName: "Adaptive MFA",
    description: "Risk-based MFA policies.",
    capabilityModuleCategory: "MFA",
    enabled: true,
    adoptionLevel: "Fully Adopted",
    licenseCount: 12000,
    usedCount: 11780,
    moduleCost: 125000,
    owner: "Identity Platform",
    notes: "Core identity control.",
  },
  {
    id: "module-knowbe4-phisher",
    productId: "product-knowbe4",
    moduleName: "PhishER",
    description: "Phishing report triage module.",
    capabilityModuleCategory: "Phishing Simulation",
    enabled: true,
    adoptionLevel: "Low",
    licenseCount: 9000,
    usedCount: 2400,
    moduleCost: 18000,
    owner: "Security Awareness",
    notes: "Enabled but underused; needs workflow adoption plan.",
  },
  {
    id: "module-wiz-dspm",
    productId: "product-wiz",
    moduleName: "Data Security Posture",
    description: "Cloud data exposure posture analysis.",
    capabilityModuleCategory: "DSPM",
    enabled: false,
    adoptionLevel: "Not Used",
    licenseCount: 0,
    usedCount: 0,
    moduleCost: 0,
    owner: "Cloud Security Engineering",
    notes: "Not licensed in current plan.",
  },
];
