import type {
  BudgetFundingStatus,
  BudgetWorkspaceData,
  BudgetWorksheetType,
  ProcurementStatus,
  RenewalStatus,
  RowReviewState,
} from "@/types/budget";

import { cents } from "./budget-calculations";

export const budgetWorkspaceData: BudgetWorkspaceData = {
  fiscalYears: [
    {
      id: "fy-2025",
      label: "FY2025",
      startsOn: "2024-07-01",
      endsOn: "2025-06-30",
    },
    {
      id: "fy-2026",
      label: "FY2026",
      startsOn: "2025-07-01",
      endsOn: "2026-06-30",
    },
    {
      id: "fy-2027",
      label: "FY2027",
      startsOn: "2026-07-01",
      endsOn: "2027-06-30",
    },
  ],
  accounts: [
    {
      id: "acct-62050",
      code: "62050",
      name: "Conference Registration / Staff Development",
      defaultWorksheet: "Conferences",
      active: true,
      sortOrder: 10,
    },
    {
      id: "acct-62026",
      code: "62026",
      name: "Business Travel",
      defaultWorksheet: "Travel",
      active: true,
      sortOrder: 20,
    },
    {
      id: "acct-62081",
      code: "62081",
      name: "Organizational Dues",
      defaultWorksheet: "Organizational Dues",
      active: true,
      sortOrder: 30,
    },
    {
      id: "acct-62094",
      code: "62094",
      name: "Software / Software as a Service",
      defaultWorksheet: "Software and SaaS",
      active: true,
      sortOrder: 40,
    },
    {
      id: "acct-62460",
      code: "62460",
      name: "Training Fees",
      defaultWorksheet: "Training",
      active: true,
      sortOrder: 50,
    },
    {
      id: "acct-62225",
      code: "62225",
      name: "Professional Services",
      defaultWorksheet: "Professional Services",
      active: true,
      sortOrder: 60,
    },
    {
      id: "acct-63256",
      code: "63256",
      name: "Maintenance Contracts",
      defaultWorksheet: "Software and SaaS",
      active: true,
      sortOrder: 70,
    },
  ],
  plans: [
    {
      id: "plan-fy-2025",
      fiscalYearId: "fy-2025",
      fiscalYear: "FY2025",
      name: "FY2025 Cybersecurity Budget",
      status: "Closed",
      version: "Final Approved",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2024-09-15",
      createdAt: "2024-05-10",
      updatedAt: "2025-06-30",
      assumptions: "Historical entry from Finance worksheets.",
      executiveNarrative: "Closed historical baseline for comparison.",
    },
    {
      id: "plan-fy-2026",
      fiscalYearId: "fy-2026",
      fiscalYear: "FY2026",
      name: "FY2026 Cybersecurity Budget",
      status: "Approved",
      version: "Final Approved",
      priorFiscalYear: "FY2025",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2025-09-15",
      createdAt: "2025-05-15",
      updatedAt: "2026-06-30",
      assumptions: "Approved baseline for FY2027 comparison.",
      executiveNarrative: "Identity, endpoint, renewal, and training baseline.",
    },
    {
      id: "plan-fy-2027",
      fiscalYearId: "fy-2027",
      fiscalYear: "FY2027",
      name: "FY2027 Cybersecurity Budget",
      status: "In Review",
      version: "Tracked Budget",
      priorFiscalYear: "FY2026",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2026-09-15",
      createdAt: "2026-05-15",
      updatedAt: "2026-07-10",
      assumptions: "Tracked fiscal-year amounts from supporting worksheets.",
      executiveNarrative:
        "Tracked cybersecurity operating budget for Finance review.",
    },
  ],
  items: [
    {
      id: "item-onetrust",
      name: "OneTrust Platform Enterprise",
      description: "Privacy and third-party risk platform.",
      vendorId: "onetrust",
      resellerId: "carahsoft",
      contractId: "contract-onetrust",
      productId: "product-onetrust",
      owner: "Maria Santos",
      strategicProgramArea: "Governance, Risk & Compliance",
      active: true,
    },
    {
      id: "item-rapid7",
      name: "Rapid7 InsightIDR",
      description: "Detection and response renewal.",
      vendorId: "rapid7",
      resellerId: "dlt",
      contractId: "contract-rapid7",
      productId: "product-rapid7",
      owner: "David Kim",
      strategicProgramArea: "Security Operations",
      active: true,
    },
    {
      id: "item-sentinelone",
      name: "SentinelOne Endpoint Protection Complete",
      description: "Endpoint detection and protection renewal.",
      vendorId: "sentinelone",
      resellerId: "shi",
      contractId: "contract-s1",
      productId: "product-s1",
      owner: "James Lee",
      strategicProgramArea: "Endpoint Security",
      active: true,
    },
    {
      id: "item-microsoft-g5",
      name: "Microsoft 365 G5 Unified Security",
      description: "Identity, endpoint, and compliance licensing.",
      vendorId: "microsoft",
      resellerId: "shi",
      contractId: "contract-ms-g5",
      productId: "product-ms-g5",
      owner: "Priya Shah",
      strategicProgramArea: "Identity & Access Management",
      active: true,
    },
    {
      id: "item-mimecast",
      name: "Mimecast Email Security",
      description: "Email security and continuity platform.",
      vendorId: "mimecast",
      resellerId: "cdwg",
      contractId: "contract-mimecast",
      productId: "product-mimecast",
      owner: "Sam Patel",
      strategicProgramArea: "Messaging Security",
      active: true,
    },
    {
      id: "item-knowbe4",
      name: "KnowBe4 Security Awareness",
      description: "Workforce security awareness and phishing simulation.",
      vendorId: "knowbe4",
      productId: "product-knowbe4",
      owner: "Alex Morgan",
      strategicProgramArea: "Workforce Security Awareness",
      active: true,
    },
    {
      id: "item-sans",
      name: "SANS Training Vouchers",
      description: "Technical training vouchers.",
      vendorId: "sans",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-rsa",
      name: "RSA Conference",
      description: "Executive and practitioner conference attendance.",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-blackhat",
      name: "Black Hat",
      description: "Technical security conference attendance.",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-gartner-srm",
      name: "Gartner Security and Risk Management",
      description: "Leadership conference attendance.",
      owner: "Maria Santos",
      strategicProgramArea: "Governance, Risk & Compliance",
      active: true,
    },
    {
      id: "item-membership",
      name: "Security Memberships and Dues",
      description: "Organizational dues and certifications.",
      owner: "Jennifer Morris",
      strategicProgramArea: "Security Leadership",
      active: true,
    },
    {
      id: "item-pro-services",
      name: "Cloud Security Architecture Assessment",
      description: "Professional services assessment.",
      vendorId: "guidepoint",
      owner: "Taylor Reed",
      strategicProgramArea: "Cloud Security",
      active: true,
    },
    {
      id: "item-retired-vpn",
      name: "Legacy VPN Token Platform",
      description: "Retired authentication product.",
      owner: "Priya Shah",
      strategicProgramArea: "Identity & Access Management",
      active: false,
    },
  ],
  annualFinancials: [
    makeAnnual(
      "fy25-onetrust",
      "plan-fy-2025",
      "scenario-fy-2025-final",
      "FY2025",
      "item-onetrust",
      "acct-62094",
      "Software and SaaS",
      1,
      180000,
      187740,
      187740,
      187740,
      180000,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy26-onetrust",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-onetrust",
      "acct-62094",
      "Software and SaaS",
      1,
      187740,
      195000,
      195000,
      195000,
      190000,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-onetrust",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-onetrust",
      "acct-62094",
      "Software and SaaS",
      1,
      187740,
      195000,
      187740,
      187740,
      0,
      0,
      "Requested",
      "Needs Review",
      "Negotiated renewal below initial vendor quote."
    ),
    makeAnnual(
      "fy25-rapid7",
      "plan-fy-2025",
      "scenario-fy-2025-final",
      "FY2025",
      "item-rapid7",
      "acct-63256",
      "Software and SaaS",
      2,
      84000,
      86000,
      86000,
      86000,
      84200,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy26-rapid7",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-rapid7",
      "acct-63256",
      "Software and SaaS",
      2,
      86000,
      90000,
      90000,
      90000,
      88600,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-rapid7",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-rapid7",
      "acct-63256",
      "Software and SaaS",
      2,
      86000,
      90000,
      90000,
      95000,
      0,
      0,
      "Requested",
      "Updated",
      "Known renewal quote carried into budget."
    ),
    makeAnnual(
      "fy25-s1",
      "plan-fy-2025",
      "scenario-fy-2025-final",
      "FY2025",
      "item-sentinelone",
      "acct-62094",
      "Software and SaaS",
      3,
      390000,
      405000,
      405000,
      405000,
      405000,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy26-s1",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-sentinelone",
      "acct-62094",
      "Software and SaaS",
      3,
      405000,
      420000,
      420000,
      420000,
      412000,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-s1",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-sentinelone",
      "acct-62094",
      "Software and SaaS",
      3,
      405000,
      420000,
      420000,
      430000,
      0,
      0,
      "Requested",
      "Needs Review",
      "Endpoint renewal pending reseller quote."
    ),
    makeAnnual(
      "fy26-sans",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-sans",
      "acct-62460",
      "Training",
      4,
      42000,
      50000,
      50000,
      50000,
      0,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-sans",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-sans",
      "acct-62460",
      "Training",
      4,
      50000,
      50000,
      66708,
      66708,
      0,
      0,
      "Requested",
      "Updated",
      "12 attendees at 5,559 each."
    ),
    makeAnnual(
      "fy26-rsa-conf",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-rsa",
      "acct-62050",
      "Conferences",
      5,
      5400,
      6585,
      6585,
      6585,
      0,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-rsa-conf",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-rsa",
      "acct-62050",
      "Conferences",
      5,
      6585,
      6585,
      6585,
      6585,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy27-blackhat-conf",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-blackhat",
      "acct-62050",
      "Conferences",
      6,
      7800,
      8685,
      8685,
      8685,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy27-gartner-conf",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-gartner-srm",
      "acct-62050",
      "Conferences",
      7,
      6000,
      7650,
      7650,
      7650,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy26-rsa-travel",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-rsa",
      "acct-62026",
      "Travel",
      8,
      14700,
      18000,
      18000,
      18000,
      0,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-rsa-travel",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-rsa",
      "acct-62026",
      "Travel",
      8,
      18000,
      21615,
      21615,
      21615,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy27-blackhat-travel",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-blackhat",
      "acct-62026",
      "Travel",
      9,
      15000,
      23115,
      23115,
      23115,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy27-gartner-travel",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-gartner-srm",
      "acct-62026",
      "Travel",
      10,
      12000,
      13090,
      13090,
      13090,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy26-msisac-dues",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-membership",
      "acct-62081",
      "Organizational Dues",
      11,
      2400,
      3000,
      3000,
      3000,
      0,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-msisac-dues",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-membership",
      "acct-62081",
      "Organizational Dues",
      11,
      3000,
      3000,
      3000,
      3000,
      0,
      0,
      "Requested"
    ),
    makeAnnual(
      "fy27-cism-dues",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-membership",
      "acct-62081",
      "Organizational Dues",
      12,
      0,
      0,
      1250,
      1250,
      0,
      0,
      "Requested",
      "Needs Review",
      "Professional certification renewal.",
      true
    ),
    makeAnnual(
      "fy26-pro-services",
      "plan-fy-2026",
      "scenario-fy-2026-final",
      "FY2026",
      "item-pro-services",
      "acct-62225",
      "Professional Services",
      13,
      12000,
      12000,
      12000,
      12000,
      0,
      0,
      "Approved"
    ),
    makeAnnual(
      "fy27-pro-services",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-pro-services",
      "acct-62225",
      "Professional Services",
      13,
      12000,
      12000,
      20000,
      20000,
      0,
      0,
      "Requested",
      "Needs Review",
      "New cloud architecture assessment.",
      true
    ),
    makeAnnual(
      "fy27-ms-g5",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-microsoft-g5",
      "acct-62094",
      "Software and SaaS",
      14,
      1180000,
      1250000,
      1250000,
      1285000,
      0,
      0,
      "Requested",
      "Needs Review",
      "Assumes government licensing true-up."
    ),
    makeAnnual(
      "fy27-mimecast",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-mimecast",
      "acct-63256",
      "Software and SaaS",
      15,
      170000,
      185000,
      185000,
      190000,
      0,
      0,
      "Requested",
      "Needs Review",
      "Email security renewal due in Q2."
    ),
    makeAnnual(
      "fy27-knowbe4",
      "plan-fy-2027",
      "scenario-fy-2027-initial",
      "FY2027",
      "item-knowbe4",
      "acct-62094",
      "Software and SaaS",
      16,
      78000,
      85000,
      85000,
      85000,
      0,
      0,
      "Requested"
    ),
    {
      ...makeAnnual(
        "fy27-retired-vpn",
        "plan-fy-2027",
        "scenario-fy-2027-initial",
        "FY2027",
        "item-retired-vpn",
        "acct-62094",
        "Savings and Reductions",
        17,
        75000,
        75000,
        0,
        0,
        0,
        0,
        "Deferred",
        "Retired",
        "Retired after identity consolidation."
      ),
      isRetired: true,
      savingsAmountCents: cents(75000),
    },
  ],
  softwareDetails: [
    {
      annualFinancialId: "fy27-onetrust",
      reseller: "Carahsoft",
      requestType: "Replacement",
      replaces: "Legacy vendor review tracker",
      notes: "Negotiated renewal below original quote.",
    },
    {
      annualFinancialId: "fy27-s1",
      reseller: "SHI",
      requestType: "New",
      notes: "Seat true-up expected.",
    },
    {
      annualFinancialId: "fy27-rapid7",
      reseller: "DLT Solutions",
      notes: "Maintenance account renewal tracked in Budget.",
    },
    {
      annualFinancialId: "fy27-ms-g5",
      reseller: "SHI",
      requestType: "New",
      notes: "Government agreement renewal.",
    },
    {
      annualFinancialId: "fy27-mimecast",
      reseller: "CDW-G",
      notes: "Email security maintenance renewal budget line.",
    },
    {
      annualFinancialId: "fy27-knowbe4",
      reseller: "Direct",
      requestType: "New",
      notes: "Awareness platform held flat year over year.",
    },
  ],
  trainingDetails: [
    {
      annualFinancialId: "fy26-sans",
      training: "SANS training vouchers",
      quantity: 10,
      costCents: cents(5000),
    },
    {
      annualFinancialId: "fy27-sans",
      training: "SANS training vouchers",
      quantity: 12,
      costCents: cents(5559),
    },
  ],
  conferenceDetails: [
    conference("fy26-rsa-conf", "RSA Conference", 3, 2195),
    conference("fy27-rsa-conf", "RSA Conference", 3, 2195),
    conference("fy27-blackhat-conf", "Black Hat", 3, 2895),
    conference(
      "fy27-gartner-conf",
      "Gartner Security and Risk Management",
      2,
      3825
    ),
  ],
  travelDetails: [
    travel(
      "fy26-rsa-travel",
      "RSA Conference",
      3,
      1950,
      5400,
      1260,
      240,
      360,
      8790
    ),
    travel(
      "fy27-rsa-travel",
      "RSA Conference",
      3,
      1950,
      5400,
      1260,
      240,
      360,
      12405
    ),
    travel(
      "fy27-blackhat-travel",
      "Black Hat",
      3,
      1950,
      5400,
      1260,
      240,
      360,
      13905
    ),
    travel(
      "fy27-gartner-travel",
      "Gartner Security and Risk Management",
      2,
      1400,
      4200,
      840,
      160,
      240,
      6250
    ),
  ],
  professionalServicesDetails: [
    {
      annualFinancialId: "fy26-pro-services",
      vendor: "GuidePoint Security",
      productOrEmployee: "Cloud security architecture advisory",
      amount: 80,
      rateCents: cents(150),
    },
    {
      annualFinancialId: "fy27-pro-services",
      vendor: "GuidePoint Security",
      productOrEmployee: "Cloud security architecture assessment",
      amount: 160,
      rateCents: cents(125),
    },
  ],
  hardwareDetails: [],
  membershipDetails: [
    {
      annualFinancialId: "fy26-msisac-dues",
      employee: "Jennifer Morris",
      organization: "MS-ISAC",
      certification: "Membership",
      annualFeeCents: cents(3000),
    },
    {
      annualFinancialId: "fy27-msisac-dues",
      employee: "Jennifer Morris",
      organization: "MS-ISAC",
      certification: "Membership",
      annualFeeCents: cents(3000),
    },
    {
      annualFinancialId: "fy27-cism-dues",
      employee: "Alex Morgan",
      organization: "ISACA",
      certification: "CISM Renewal",
      annualFeeCents: cents(1250),
    },
  ],
  personnelDetails: [],
  maintenanceRenewals: [
    renewal(
      "renewal-s1",
      "fy27-s1",
      "SentinelOne",
      "Endpoint Protection Complete",
      "SHI",
      420000,
      430000,
      425000,
      "2027-10-01",
      "2028-09-30",
      90,
      "acct-62094",
      "Quote Received",
      "Under Review",
      "James Lee",
      "Medium",
      "Carry forward quote while seat true-up is validated."
    ),
    renewal(
      "renewal-onetrust",
      "fy27-onetrust",
      "OneTrust",
      "OneTrust Platform Enterprise",
      "Carahsoft",
      195000,
      212900,
      187740,
      "2027-01-15",
      "2028-01-31",
      180,
      "acct-62094",
      "Negotiating",
      "In Preparation",
      "Maria Santos",
      "High",
      "Negotiated concession creates budget savings."
    ),
    renewal(
      "renewal-rapid7",
      "fy27-rapid7",
      "Rapid7",
      "InsightIDR",
      "DLT Solutions",
      90000,
      104500,
      95000,
      "2026-09-30",
      "2027-09-29",
      90,
      "acct-63256",
      "Budget Confirmed",
      "Approved",
      "David Kim",
      "Medium",
      "Quote feeds maintenance account request."
    ),
    renewal(
      "renewal-mimecast",
      "fy27-mimecast",
      "Mimecast",
      "Email Security",
      "CDW-G",
      185000,
      201000,
      190000,
      "2027-03-01",
      "2028-02-29",
      60,
      "acct-63256",
      "Quote Requested",
      "Not Started",
      "Sam Patel",
      "Low",
      "Renew unless email consolidation changes scope."
    ),
    renewal(
      "renewal-ms-g5",
      "fy27-ms-g5",
      "Microsoft",
      "Microsoft 365 G5",
      "SHI",
      1250000,
      1285000,
      1285000,
      "2027-07-01",
      "2028-06-30",
      90,
      "acct-62094",
      "Planning",
      "Not Started",
      "Priya Shah",
      "Critical",
      "True-up must be confirmed before final submission."
    ),
    renewal(
      "renewal-knowbe4",
      "fy27-knowbe4",
      "KnowBe4",
      "Security Awareness Training",
      "Direct",
      85000,
      85000,
      85000,
      "2027-02-01",
      "2028-01-31",
      60,
      "acct-62094",
      "Approved",
      "Not Required",
      "Alex Morgan",
      "Low",
      "Renewal flat to current year."
    ),
  ],
  savingsRecords: [
    {
      id: "savings-onetrust",
      budgetPlanId: "plan-fy-2027",
      annualFinancialId: "fy27-onetrust",
      renewalId: "renewal-onetrust",
      type: "Contract negotiation",
      description: "Negotiated OneTrust renewal below initial quote.",
      amountCents: cents(25160),
      costAvoidanceCents: 0,
      isBudgetReduction: true,
      owner: "Maria Santos",
    },
    {
      id: "savings-retired-vpn",
      budgetPlanId: "plan-fy-2027",
      annualFinancialId: "fy27-retired-vpn",
      type: "Product retirement",
      description:
        "Retired legacy VPN token platform after identity consolidation.",
      amountCents: cents(75000),
      costAvoidanceCents: 0,
      isBudgetReduction: true,
      owner: "Priya Shah",
    },
    {
      id: "avoidance-sase",
      budgetPlanId: "plan-fy-2027",
      type: "Avoided purchase",
      description:
        "Deferred duplicate secure web gateway purchase pending architecture review.",
      amountCents: 0,
      costAvoidanceCents: cents(140000),
      isBudgetReduction: false,
      owner: "Sam Patel",
    },
  ],
};

function makeAnnual(
  id: string,
  budgetPlanId: string,
  scenarioId: string,
  fiscalYear: string,
  budgetItemId: string,
  accountId: string,
  worksheet: BudgetWorksheetType,
  sortOrder: number,
  priorApproved: number,
  currentApproved: number,
  base: number,
  proposed: number,
  actual: number,
  savings: number,
  fundingStatus: BudgetFundingStatus,
  reviewState: RowReviewState = "Reviewed",
  comments = "",
  isNewRequest = false
): BudgetWorkspaceData["annualFinancials"][number] {
  return {
    id,
    budgetPlanId,
    scenarioId,
    fiscalYear,
    budgetItemId,
    accountId,
    worksheet,
    sortOrder,
    priorApprovedAmountCents: cents(priorApproved),
    currentApprovedAmountCents: cents(currentApproved),
    baseAmountCents: cents(base),
    requestedAmountCents: cents(proposed),
    proposedAmountCents: cents(proposed),
    approvedAmountCents: fundingStatus === "Approved" ? cents(proposed) : 0,
    revisedApprovedAmountCents: 0,
    forecastAmountCents: cents(proposed),
    encumberedAmountCents: 0,
    actualAmountCents: cents(actual),
    unitCostCents: cents(proposed),
    quantity: 1,
    oneTimeAmountCents: isNewRequest ? cents(proposed) : 0,
    recurringAmountCents: isNewRequest ? 0 : cents(proposed),
    savingsAmountCents: cents(savings),
    costAvoidanceAmountCents: 0,
    fundingStatus,
    recurrence: isNewRequest ? "One-Time" : "Recurring",
    reviewState,
    isNewRequest,
    isRecurring: !isNewRequest,
    isOneTime: isNewRequest,
    isRetired: false,
    comments,
    businessJustification:
      isNewRequest || fundingStatus === "Requested"
        ? "Supports cybersecurity risk reduction and Finance planning visibility."
        : "Baseline cybersecurity operating expense.",
    riskIfNotFunded:
      "Service disruption, control degradation, or delayed security roadmap execution.",
    owner: "",
  };
}

function conference(
  annualFinancialId: string,
  conferenceName: string,
  attendees: number,
  registrationFee: number
) {
  return {
    annualFinancialId,
    conference: conferenceName,
    attendees,
    registrationFeeCents: cents(registrationFee),
  };
}

function travel(
  annualFinancialId: string,
  conferenceOrTrip: string,
  attendees: number,
  airfare: number,
  hotel: number,
  perDiem: number,
  luggage: number,
  parking: number,
  taxiUber: number
) {
  return {
    annualFinancialId,
    conferenceOrTrip,
    attendees,
    airfareCents: cents(airfare),
    hotelCents: cents(hotel),
    perDiemCents: cents(perDiem),
    luggageCents: cents(luggage),
    parkingCents: cents(parking),
    taxiUberCents: cents(taxiUber),
  };
}

function renewal(
  id: string,
  linkedAnnualFinancialId: string,
  vendor: string,
  productOrService: string,
  reseller: string,
  currentCost: number,
  renewalQuote: number,
  negotiatedCost: number,
  renewalDate: string,
  contractEnd: string,
  noticePeriodDays: number,
  fundingAccountId: string,
  renewalStatus: RenewalStatus,
  procurementStatus: ProcurementStatus,
  renewalOwner: string,
  renewalRisk: BudgetWorkspaceData["maintenanceRenewals"][number]["renewalRisk"],
  notes: string
): BudgetWorkspaceData["maintenanceRenewals"][number] {
  const contractStartYear = Number(contractEnd.slice(0, 4)) - 1;
  return {
    id,
    budgetPlanId: "plan-fy-2027",
    linkedAnnualFinancialId,
    vendor,
    productOrService,
    reseller,
    currentCostCents: cents(currentCost),
    renewalQuoteCents: cents(renewalQuote),
    negotiatedCostCents: cents(negotiatedCost),
    renewalDate,
    contractStart: `${contractStartYear}${contractEnd.slice(4)}`,
    contractEnd,
    noticePeriodDays,
    autoRenewal: renewalRisk === "Critical",
    paymentFrequency: "Annual",
    fundingAccountId,
    renewalStatus,
    procurementStatus,
    quoteReceivedDate:
      renewalStatus === "Quote Received" || renewalStatus === "Negotiating"
        ? "2026-06-15"
        : undefined,
    purchaseRequestNumber:
      procurementStatus === "Approved" ? "PR-FY27-REN-003" : undefined,
    purchaseOrderNumber:
      procurementStatus === "Purchase Order Issued"
        ? "PO-FY27-REN-003"
        : undefined,
    expectedPaymentDate: "2027-07-15",
    renewalOwner,
    procurementOwner: "Casey Nguyen",
    renewalStrategy: notes,
    renewalRisk,
    notes,
  };
}
