import type {
  BudgetFundingStatus,
  BudgetWorkspaceData,
  BudgetWorksheetType,
  ProcurementStatus,
  RenewalStatus,
  RowReviewState,
} from "@/types/budget";

import { cents } from "./budget-calculations";

export const budgetWorkspaceData: BudgetWorkspaceData = {
  fiscalYears: [
    {
      id: "fy-2025",
      label: "FY2025",
      startsOn: "2024-07-01",
      endsOn: "2025-06-30",
    },
    {
      id: "fy-2026",
      label: "FY2026",
      startsOn: "2025-07-01",
      endsOn: "2026-06-30",
    },
    {
      id: "fy-2027",
      label: "FY2027",
      startsOn: "2026-07-01",
      endsOn: "2027-06-30",
    },
  ],
  accounts: [
    {
      id: "acct-62050",
      code: "62050",
      name: "Conference / Staff Development",
      defaultWorksheet: "Travel and Conferences",
      active: true,
      sortOrder: 10,
    },
    {
      id: "acct-62081",
      code: "62081",
      name: "Organizational Dues",
      defaultWorksheet: "Organizational Dues",
      active: true,
      sortOrder: 20,
    },
    {
      id: "acct-62093",
      code: "62093",
      name: "Computer Hardware",
      defaultWorksheet: "Hardware",
      active: true,
      sortOrder: 30,
    },
    {
      id: "acct-62094",
      code: "62094",
      name: "Software / Software as a Service",
      defaultWorksheet: "Software and SaaS",
      active: true,
      sortOrder: 40,
    },
    {
      id: "acct-62460",
      code: "62460",
      name: "Training Fees",
      defaultWorksheet: "Training",
      active: true,
      sortOrder: 50,
    },
    {
      id: "acct-62026",
      code: "62026",
      name: "Business Travel",
      defaultWorksheet: "Travel and Conferences",
      active: true,
      sortOrder: 60,
    },
    {
      id: "acct-62225",
      code: "62225",
      name: "Professional Services",
      defaultWorksheet: "Professional Services",
      active: true,
      sortOrder: 70,
    },
    {
      id: "acct-63256",
      code: "63256",
      name: "Maintenance Contracts",
      defaultWorksheet: "Maintenance Renewals",
      active: true,
      sortOrder: 80,
    },
  ],
  plans: [
    {
      id: "plan-fy-2025",
      fiscalYearId: "fy-2025",
      fiscalYear: "FY2025",
      name: "FY2025 Cybersecurity Budget",
      status: "Closed",
      version: "Final Approved",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2024-09-15",
      createdAt: "2024-05-10",
      updatedAt: "2025-06-30",
      assumptions: "Historical entry from Finance worksheets.",
      executiveNarrative: "Closed historical baseline for comparison.",
    },
    {
      id: "plan-fy-2026",
      fiscalYearId: "fy-2026",
      fiscalYear: "FY2026",
      name: "FY2026 Cybersecurity Budget",
      status: "Approved",
      version: "Final Approved",
      priorFiscalYear: "FY2025",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2025-09-15",
      createdAt: "2025-05-15",
      updatedAt: "2026-06-30",
      assumptions: "Approved baseline for FY2027 roll-forward.",
      executiveNarrative: "Identity, endpoint, renewal, and training baseline.",
    },
    {
      id: "plan-fy-2027",
      fiscalYearId: "fy-2027",
      fiscalYear: "FY2027",
      name: "FY2027 Cybersecurity Budget",
      status: "Draft",
      version: "Initial Request",
      priorFiscalYear: "FY2026",
      planningOwner: "Jennifer Morris",
      submissionDueDate: "2026-09-15",
      createdAt: "2026-05-15",
      updatedAt: "2026-07-10",
      assumptions:
        "Renewals roll forward from current approved values with known quotes where available.",
      executiveNarrative:
        "Draft request prioritizes maintenance renewals, identity controls, staff training, and selective new risk reduction.",
    },
  ],
  scenarios: [
    {
      id: "scenario-fy-2027-initial",
      budgetPlanId: "plan-fy-2027",
      label: "Initial Request",
      description: "Working request before executive reduction review.",
      isActive: true,
    },
    {
      id: "scenario-fy-2027-recommended",
      budgetPlanId: "plan-fy-2027",
      label: "Recommended",
      description: "CISO recommended submission target.",
      isActive: false,
    },
    {
      id: "scenario-fy-2026-final",
      budgetPlanId: "plan-fy-2026",
      label: "Final Approved",
      description: "Approved FY2026 baseline.",
      isActive: true,
    },
    {
      id: "scenario-fy-2025-final",
      budgetPlanId: "plan-fy-2025",
      label: "Final Approved",
      description: "Historical approved baseline.",
      isActive: true,
    },
  ],
  items: [
    {
      id: "item-onetrust",
      name: "OneTrust Platform Enterprise",
      description: "Privacy and third-party risk platform.",
      vendorId: "onetrust",
      resellerId: "carahsoft",
      contractId: "contract-onetrust",
      productId: "product-onetrust",
      owner: "Maria Santos",
      strategicProgramArea: "Governance, Risk & Compliance",
      active: true,
    },
    {
      id: "item-rapid7",
      name: "Rapid7 InsightIDR",
      description: "Detection and response renewal.",
      vendorId: "rapid7",
      resellerId: "dlt",
      contractId: "contract-rapid7",
      productId: "product-rapid7",
      owner: "David Kim",
      strategicProgramArea: "Security Operations",
      active: true,
    },
    {
      id: "item-sentinelone",
      name: "SentinelOne Endpoint Protection Complete",
      description: "Endpoint detection and protection renewal.",
      vendorId: "sentinelone",
      resellerId: "shi",
      contractId: "contract-s1",
      productId: "product-s1",
      owner: "James Lee",
      strategicProgramArea: "Endpoint Security",
      active: true,
    },
    {
      id: "item-microsoft-g5",
      name: "Microsoft 365 G5 Unified Security",
      description: "Identity, endpoint, and compliance government licensing.",
      vendorId: "microsoft",
      resellerId: "shi",
      contractId: "contract-ms-g5",
      productId: "product-ms-g5",
      owner: "Priya Shah",
      strategicProgramArea: "Identity & Access Management",
      active: true,
    },
    {
      id: "item-mimecast",
      name: "Mimecast Email Security",
      description: "Email security and continuity platform.",
      vendorId: "mimecast",
      resellerId: "cdwg",
      contractId: "contract-mimecast",
      productId: "product-mimecast",
      owner: "Sam Patel",
      strategicProgramArea: "Network Security",
      active: true,
    },
    {
      id: "item-knowbe4",
      name: "KnowBe4 Security Awareness",
      description: "Workforce security awareness and phishing simulation.",
      vendorId: "knowbe4",
      productId: "product-knowbe4",
      owner: "Alex Morgan",
      strategicProgramArea: "Workforce Security Awareness",
      active: true,
    },
    {
      id: "item-sans",
      name: "SANS Institute Technical Training",
      description: "Security staff training vouchers.",
      vendorId: "sans",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-rsa",
      name: "RSA Conference",
      description: "Executive and practitioner conference attendance.",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-defcon",
      name: "DEF CON",
      description: "Security research conference attendance.",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-blackhat",
      name: "Black Hat",
      description: "Technical security conference attendance.",
      owner: "Lisa Grant",
      strategicProgramArea: "Cybersecurity Staff Training & Development",
      active: true,
    },
    {
      id: "item-gartner-srm",
      name: "Gartner Security and Risk Management",
      description: "Leadership conference attendance.",
      owner: "Maria Santos",
      strategicProgramArea: "Governance, Risk & Compliance",
      active: true,
    },
    {
      id: "item-gartner-iam",
      name: "Gartner Identity and Access Management",
      description: "Identity leadership conference attendance.",
      owner: "Priya Shah",
      strategicProgramArea: "Identity & Access Management",
      active: true,
    },
    {
      id: "item-tagitm",
      name: "TAGITM",
      description: "Government technology conference attendance.",
      owner: "Jennifer Morris",
      strategicProgramArea: "Security Leadership",
      active: true,
    },
    {
      id: "item-secureworld",
      name: "SecureWorld Dallas",
      description: "Regional cybersecurity conference attendance.",
      owner: "Jennifer Morris",
      strategicProgramArea: "Security Leadership",
      active: true,
    },
    {
      id: "item-pro-services",
      name: "Cloud Security Architecture Assessment",
      description: "Professional services assessment.",
      vendorId: "guidepoint",
      owner: "Taylor Reed",
      strategicProgramArea: "Cloud Security",
      active: true,
    },
    {
      id: "item-hardware",
      name: "Secure Network Appliance Refresh",
      description: "Replacement hardware for secure network edge.",
      vendorId: "palo-alto",
      resellerId: "cdwg",
      owner: "Sam Patel",
      strategicProgramArea: "Network Security",
      active: true,
    },
    {
      id: "item-membership",
      name: "MS-ISAC Membership",
      description: "Security organization dues.",
      owner: "Jennifer Morris",
      strategicProgramArea: "Security Leadership",
      active: true,
    },
    {
      id: "item-personnel",
      name: "Senior Cloud Security Engineer",
      description: "New position request with loaded cost.",
      owner: "Taylor Reed",
      strategicProgramArea: "Cloud Security",
      active: true,
    },
    {
      id: "item-retired-vpn",
      name: "Legacy VPN Token Platform",
      description: "Retired authentication product.",
      owner: "Priya Shah",
      strategicProgramArea: "Identity & Access Management",
      active: false,
    },
  ],
  annualFinancials: [
    makeAnnual("fy25-onetrust", "plan-fy-2025", "scenario-fy-2025-final", "FY2025", "item-onetrust", "acct-62094", "Software and SaaS", 1, 180000, 187740, 187740, 187740, 180000, 0, "Approved"),
    makeAnnual("fy26-onetrust", "plan-fy-2026", "scenario-fy-2026-final", "FY2026", "item-onetrust", "acct-62094", "Software and SaaS", 1, 187740, 195000, 195000, 195000, 190000, 0, "Approved"),
    makeAnnual("fy27-onetrust", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-onetrust", "acct-62094", "Software and SaaS", 1, 187740, 195000, 187740, 187740, 0, 0, "Requested", "Needs Review", "Renewal quote negotiated below initial vendor quote."),
    makeAnnual("fy25-rapid7", "plan-fy-2025", "scenario-fy-2025-final", "FY2025", "item-rapid7", "acct-63256", "Maintenance Renewals", 2, 84000, 86000, 86000, 86000, 84200, 0, "Approved"),
    makeAnnual("fy26-rapid7", "plan-fy-2026", "scenario-fy-2026-final", "FY2026", "item-rapid7", "acct-63256", "Maintenance Renewals", 2, 86000, 90000, 90000, 90000, 88600, 0, "Approved"),
    makeAnnual("fy27-rapid7", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-rapid7", "acct-63256", "Maintenance Renewals", 2, 86000, 90000, 90000, 95000, 0, 0, "Recommended", "Updated", "Known renewal quote carried into budget."),
    makeAnnual("fy25-s1", "plan-fy-2025", "scenario-fy-2025-final", "FY2025", "item-sentinelone", "acct-62094", "Software and SaaS", 3, 390000, 405000, 405000, 405000, 405000, 0, "Approved"),
    makeAnnual("fy26-s1", "plan-fy-2026", "scenario-fy-2026-final", "FY2026", "item-sentinelone", "acct-62094", "Software and SaaS", 3, 405000, 420000, 420000, 420000, 412000, 0, "Approved"),
    makeAnnual("fy27-s1", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-sentinelone", "acct-62094", "Software and SaaS", 3, 405000, 420000, 420000, 430000, 0, 0, "Requested", "Needs Review", "Endpoint renewal pending reseller quote."),
    makeAnnual("fy27-ms-g5", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-microsoft-g5", "acct-62094", "Software and SaaS", 4, 1180000, 1250000, 1250000, 1285000, 0, 0, "Requested", "Needs Review", "Assumes government licensing true-up."),
    makeAnnual("fy27-mimecast", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-mimecast", "acct-63256", "Maintenance Renewals", 5, 170000, 185000, 185000, 190000, 0, 0, "Requested", "Needs Review", "Email security renewal due in Q2."),
    makeAnnual("fy27-knowbe4", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-knowbe4", "acct-62094", "Software and SaaS", 6, 78000, 85000, 85000, 85000, 0, 0, "Recommended"),
    makeAnnual("fy27-sans", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-sans", "acct-62460", "Training", 7, 60000, 60000, 66708, 66708, 0, 0, "Requested", "Updated", "12 attendees at 5,559 each."),
    makeAnnual("fy27-rsa", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-rsa", "acct-62050", "Travel and Conferences", 8, 24000, 26000, 28200, 28200, 0, 0, "Requested"),
    makeAnnual("fy27-defcon", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-defcon", "acct-62026", "Travel and Conferences", 9, 12000, 15000, 17700, 17700, 0, 0, "Requested"),
    makeAnnual("fy27-blackhat", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-blackhat", "acct-62050", "Travel and Conferences", 10, 21000, 24000, 31800, 31800, 0, 0, "Requested"),
    makeAnnual("fy27-gartner-srm", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-gartner-srm", "acct-62050", "Travel and Conferences", 11, 18000, 21000, 24200, 24200, 0, 0, "Requested"),
    makeAnnual("fy27-gartner-iam", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-gartner-iam", "acct-62050", "Travel and Conferences", 12, 0, 0, 12100, 12100, 0, 0, "Requested", "Needs Review", "New identity conference request."),
    makeAnnual("fy27-tagitm", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-tagitm", "acct-62026", "Travel and Conferences", 13, 4200, 4800, 5400, 5400, 0, 0, "Recommended"),
    makeAnnual("fy27-secureworld", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-secureworld", "acct-62026", "Travel and Conferences", 14, 3000, 3500, 4200, 4200, 0, 0, "Recommended"),
    makeAnnual("fy27-pro-services", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-pro-services", "acct-62225", "Professional Services", 15, 0, 0, 20000, 20000, 0, 0, "Requested", "Needs Review", "New cloud architecture assessment.", true),
    makeAnnual("fy27-hardware", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-hardware", "acct-62093", "Hardware", 16, 95000, 110000, 138500, 138500, 0, 0, "Requested", "Needs Review", "Replacement appliance request."),
    makeAnnual("fy27-membership", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-membership", "acct-62081", "Organizational Dues", 17, 2500, 3000, 3000, 3000, 0, 0, "Recommended"),
    makeAnnual("fy27-personnel", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-personnel", "acct-62094", "Personnel", 18, 0, 0, 185000, 185000, 0, 0, "Requested", "Needs Review", "New cloud security engineer request.", true),
    {
      ...makeAnnual("fy27-retired-vpn", "plan-fy-2027", "scenario-fy-2027-initial", "FY2027", "item-retired-vpn", "acct-62094", "Savings and Reductions", 19, 75000, 75000, 0, 0, 0, 0, "Deferred", "Retired", "Retired after identity consolidation."),
      isRetired: true,
      savingsAmountCents: cents(75000),
    },
  ],
  softwareDetails: [
    {
      annualFinancialId: "fy27-onetrust",
      vendor: "OneTrust",
      productOrService: "OneTrust Platform Enterprise",
      reseller: "Carahsoft",
      newOrRenewal: "Renewal",
      contract: "OneTrust Platform Enterprise",
      renewalDate: "2027-01-15",
      contractStart: "2027-02-01",
      contractEnd: "2028-01-31",
      paymentFrequency: "Annual",
      notes: "Negotiated renewal below original quote.",
    },
    {
      annualFinancialId: "fy27-s1",
      vendor: "SentinelOne",
      productOrService: "Endpoint Protection Complete",
      reseller: "SHI",
      newOrRenewal: "Renewal",
      contract: "SentinelOne Endpoint Protection",
      renewalDate: "2027-10-01",
      contractStart: "2027-10-01",
      contractEnd: "2028-09-30",
      paymentFrequency: "Annual",
      notes: "Seat true-up expected.",
    },
    {
      annualFinancialId: "fy27-ms-g5",
      vendor: "Microsoft",
      productOrService: "Microsoft 365 G5",
      reseller: "SHI",
      newOrRenewal: "Renewal",
      contract: "Microsoft G5 Unified Support",
      renewalDate: "2027-07-01",
      contractStart: "2027-07-01",
      contractEnd: "2028-06-30",
      paymentFrequency: "Annual",
      notes: "Government agreement renewal.",
    },
  ],
  trainingDetails: [
    {
      annualFinancialId: "fy27-sans",
      provider: "SANS Institute",
      program: "Technical training vouchers",
      attendees: 12,
      costPerPersonCents: cents(5559),
      travelRequired: false,
    },
  ],
  travelDetails: [
    travel("fy27-rsa", "RSA Conference", 3, 2195, 650, 1800, 420, 80, 120, 260, 75),
    travel("fy27-defcon", "DEF CON", 3, 560, 500, 1100, 300, 60, 90, 210, 80),
    travel("fy27-blackhat", "Black Hat", 3, 2895, 650, 1800, 420, 80, 120, 260, 375),
    travel("fy27-gartner-srm", "Gartner Security and Risk Management", 2, 3825, 700, 2100, 420, 80, 120, 260, 595),
    travel("fy27-gartner-iam", "Gartner Identity and Access Management", 1, 3825, 700, 2100, 420, 80, 120, 260, 595),
    travel("fy27-tagitm", "TAGITM", 3, 450, 0, 900, 180, 0, 90, 120, 60),
    travel("fy27-secureworld", "SecureWorld Dallas", 6, 395, 0, 0, 120, 0, 60, 75, 50),
  ],
  professionalServicesDetails: [
    {
      annualFinancialId: "fy27-pro-services",
      vendor: "GuidePoint Security",
      productOrService: "Cloud security architecture assessment",
      quantityOrHours: 1,
      rateCents: cents(20000),
      deliverables: "Architecture review, findings brief, and remediation roadmap.",
      project: "Cloud security operating model",
      plannedStart: "2026-10-01",
      plannedEnd: "2026-12-15",
    },
  ],
  hardwareDetails: [
    {
      annualFinancialId: "fy27-hardware",
      vendor: "Palo Alto Networks",
      equipment: "Secure network appliances",
      quantity: 2,
      unitCostCents: cents(57500),
      installationCents: cents(12500),
      maintenanceCents: cents(11000),
      replacementOrNew: "Replacement",
      replaces: "Aging perimeter appliances",
    },
  ],
  membershipDetails: [
    {
      annualFinancialId: "fy27-membership",
      organization: "MS-ISAC",
      membershipType: "Government security membership",
      memberCount: 3,
      costPerMemberCents: cents(1000),
      renewalDate: "2027-04-01",
    },
  ],
  personnelDetails: [
    {
      annualFinancialId: "fy27-personnel",
      positionTitle: "Senior Cloud Security Engineer",
      positionType: "New",
      positionCount: 1,
      salaryCents: cents(145000),
      benefitsCents: cents(40000),
      proposedStartDate: "2027-01-01",
    },
  ],
  maintenanceRenewals: [
    renewal("renewal-s1", "fy27-s1", "SentinelOne", "Endpoint Protection Complete", "SHI", 420000, 430000, 425000, "2027-10-01", "2028-09-30", 90, "acct-62094", "Quote Received", "Under Review", "James Lee", "Medium", "Carry forward quote while seat true-up is validated."),
    renewal("renewal-onetrust", "fy27-onetrust", "OneTrust", "OneTrust Platform Enterprise", "Carahsoft", 195000, 212900, 187740, "2027-01-15", "2028-01-31", 180, "acct-62094", "Negotiating", "In Preparation", "Maria Santos", "High", "Negotiated concession creates budget savings."),
    renewal("renewal-rapid7", "fy27-rapid7", "Rapid7", "InsightIDR", "DLT Solutions", 90000, 104500, 95000, "2026-09-30", "2027-09-29", 90, "acct-63256", "Budget Confirmed", "Approved", "David Kim", "Medium", "Quote feeds maintenance account request."),
    renewal("renewal-mimecast", "fy27-mimecast", "Mimecast", "Email Security", "CDW-G", 185000, 201000, 190000, "2027-03-01", "2028-02-29", 60, "acct-63256", "Quote Requested", "Not Started", "Sam Patel", "Low", "Renew unless email consolidation changes scope."),
    renewal("renewal-ms-g5", "fy27-ms-g5", "Microsoft", "Microsoft 365 G5", "SHI", 1250000, 1285000, 1285000, "2027-07-01", "2028-06-30", 90, "acct-62094", "Planning", "Not Started", "Priya Shah", "Critical", "True-up must be confirmed before final submission."),
    renewal("renewal-knowbe4", "fy27-knowbe4", "KnowBe4", "Security Awareness Training", "Direct", 85000, 85000, 85000, "2027-02-01", "2028-01-31", 60, "acct-62094", "Approved", "Not Required", "Alex Morgan", "Low", "Renewal flat to current year."),
  ],
  savingsRecords: [
    {
      id: "savings-onetrust",
      budgetPlanId: "plan-fy-2027",
      annualFinancialId: "fy27-onetrust",
      renewalId: "renewal-onetrust",
      type: "Contract negotiation",
      description: "Negotiated OneTrust renewal below initial quote.",
      amountCents: cents(25160),
      costAvoidanceCents: 0,
      isBudgetReduction: true,
      owner: "Maria Santos",
    },
    {
      id: "savings-retired-vpn",
      budgetPlanId: "plan-fy-2027",
      annualFinancialId: "fy27-retired-vpn",
      type: "Product retirement",
      description: "Retired legacy VPN token platform after identity consolidation.",
      amountCents: cents(75000),
      costAvoidanceCents: 0,
      isBudgetReduction: true,
      owner: "Priya Shah",
    },
    {
      id: "avoidance-sase",
      budgetPlanId: "plan-fy-2027",
      type: "Avoided purchase",
      description: "Deferred duplicate secure web gateway purchase pending architecture review.",
      amountCents: 0,
      costAvoidanceCents: cents(140000),
      isBudgetReduction: false,
      owner: "Sam Patel",
    },
  ],
};

function makeAnnual(
  id: string,
  budgetPlanId: string,
  scenarioId: string,
  fiscalYear: string,
  budgetItemId: string,
  accountId: string,
  worksheet: BudgetWorksheetType,
  sortOrder: number,
  priorApproved: number,
  currentApproved: number,
  base: number,
  proposed: number,
  actual: number,
  savings: number,
  fundingStatus: BudgetFundingStatus,
  reviewState: RowReviewState = "Reviewed",
  comments = "",
  isNewRequest = false
): BudgetWorkspaceData["annualFinancials"][number] {
  return {
    id,
    budgetPlanId,
    scenarioId,
    fiscalYear,
    budgetItemId,
    accountId,
    worksheet,
    sortOrder,
    priorApprovedAmountCents: cents(priorApproved),
    currentApprovedAmountCents: cents(currentApproved),
    baseAmountCents: cents(base),
    requestedAmountCents: cents(proposed),
    proposedAmountCents: cents(proposed),
    approvedAmountCents: fundingStatus === "Approved" ? cents(proposed) : 0,
    revisedApprovedAmountCents: 0,
    forecastAmountCents: cents(proposed),
    encumberedAmountCents: 0,
    actualAmountCents: cents(actual),
    unitCostCents: cents(proposed),
    quantity: 1,
    oneTimeAmountCents: isNewRequest ? cents(proposed) : 0,
    recurringAmountCents: isNewRequest ? 0 : cents(proposed),
    savingsAmountCents: cents(savings),
    costAvoidanceAmountCents: 0,
    fundingStatus,
    recurrence: isNewRequest ? "One-Time" : "Recurring",
    reviewState,
    isNewRequest,
    isRecurring: !isNewRequest,
    isOneTime: isNewRequest,
    isRetired: false,
    comments,
    businessJustification:
      isNewRequest || fundingStatus === "Requested"
        ? "Supports cybersecurity risk reduction and Finance planning visibility."
        : "Baseline cybersecurity operating expense.",
    riskIfNotFunded:
      "Service disruption, control degradation, or delayed security roadmap execution.",
    owner: "",
  };
}

function travel(
  annualFinancialId: string,
  conference: string,
  attendees: number,
  registration: number,
  airfare: number,
  hotel: number,
  perDiem: number,
  luggage: number,
  parking: number,
  ground: number,
  miscellaneous: number
) {
  return {
    annualFinancialId,
    conference,
    attendees,
    registrationCents: cents(registration),
    airfareCents: cents(airfare),
    hotelCents: cents(hotel),
    perDiemCents: cents(perDiem),
    luggageCents: cents(luggage),
    parkingCents: cents(parking),
    groundCents: cents(ground),
    miscellaneousCents: cents(miscellaneous),
  };
}

function renewal(
  id: string,
  linkedAnnualFinancialId: string,
  vendor: string,
  productOrService: string,
  reseller: string,
  currentCost: number,
  renewalQuote: number,
  negotiatedCost: number,
  renewalDate: string,
  contractEnd: string,
  noticePeriodDays: number,
  fundingAccountId: string,
  renewalStatus: RenewalStatus,
  procurementStatus: ProcurementStatus,
  renewalOwner: string,
  renewalRisk: BudgetWorkspaceData["maintenanceRenewals"][number]["renewalRisk"],
  notes: string
): BudgetWorkspaceData["maintenanceRenewals"][number] {
  const contractStartYear = Number(contractEnd.slice(0, 4)) - 1;
  return {
    id,
    budgetPlanId: "plan-fy-2027",
    linkedAnnualFinancialId,
    vendor,
    productOrService,
    reseller,
    currentCostCents: cents(currentCost),
    renewalQuoteCents: cents(renewalQuote),
    negotiatedCostCents: cents(negotiatedCost),
    renewalDate,
    contractStart: `${contractStartYear}${contractEnd.slice(4)}`,
    contractEnd,
    noticePeriodDays,
    autoRenewal: renewalRisk === "Critical",
    paymentFrequency: "Annual",
    fundingAccountId,
    renewalStatus,
    procurementStatus,
    quoteReceivedDate:
      renewalStatus === "Quote Received" || renewalStatus === "Negotiating"
        ? "2026-06-15"
        : undefined,
    purchaseRequestNumber:
      procurementStatus === "Approved" ? "PR-FY27-REN-003" : undefined,
    purchaseOrderNumber:
      procurementStatus === "Purchase Order Issued" ? "PO-FY27-REN-003" : undefined,
    expectedPaymentDate: "2027-07-15",
    renewalOwner,
    procurementOwner: "Casey Nguyen",
    renewalStrategy: notes,
    renewalRisk,
    notes,
  };
}
